Move check after typost

diff --git a/debian/.devcontainer/Dockerfile b/debian/.devcontainer/Dockerfile
--- a/debian/.devcontainer/Dockerfile
+++ b/debian/.devcontainer/Dockerfile
@@ -32,11 +32,6 @@ RUN apt-get update && \
 
 COPY extras/fonts/ /usr/local/share/fonts/cm-bakoma/
 
-# Update font cache and verify that the required fonts are available
-RUN fc-cache -f -v &&  \
-    typst fonts | grep -qE '^cmr10$'     || (echo "BaKoMa CM missing" && exit 1) && \
-    typst fonts | grep -qE '^CMU Serif$' || (echo "CMU fallback missing" && exit 1)
-
 # Enable contrib repo (for fonts only - shows at duplicated)
 RUN echo "deb http://deb.debian.org/debian trixie main contrib" > /etc/apt/sources.list.d/contrib.list \
     && apt-get update \
@@ -59,5 +54,10 @@ RUN curl -fsSL \
     | tar -xJ \
     && mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/typst \
     && rm -rf typst-x86_64-unknown-linux-musl
+
+# Update font cache and verify that the required fonts are available
+RUN fc-cache -f -v &&  \
+    typst fonts | grep -qE '^cmr10$'     || (echo "BaKoMa CM missing" && exit 1) && \
+    typst fonts | grep -qE '^CMU Serif$' || (echo "CMU fallback missing" && exit 1)
 
 RUN curl -L https://coder.com/install.sh | sh
